# Tema personalizado para Streamlit basado en la nueva paleta verde y amarilla

[theme]
base="light"
primaryColor="#8EE630"  # Verde lima brillante para elementos activos y destacados
backgroundColor="#DAE630"  # Amarillo limón para el fondo principal
secondaryBackgroundColor="#30E69D"  # Verde turquesa para fondos de elementos secundarios
textColor="#293241"  # Azul oscuro profundo para texto, asegurando excelente legibilidad
font="sans serif"

[theme.fonts]
heading = "Helvetica, Arial, sans-serif"
base = "Helvetica, Arial, sans-serif"
code = "Monospace"
