# Tema personalizado para Streamlit

[theme]
base="light"
primaryColor="#007BFF"  # Un azul brillante para elementos activos y destacados
backgroundColor="#FFFFFF"  # Blanco puro para el fondo principal, aportando luminosidad y claridad
secondaryBackgroundColor="#F0F2F6"  # Un gris suave para fondos de elementos secundarios
textColor="#333333"  # Un gris oscuro casi negro para texto, asegurando excelente legibilidad
font="sans serif"

[theme.fonts]
heading = "Helvetica, Arial, sans-serif"
base = "Helvetica, Arial, sans-serif"
code = "Monospace"
