# Tema personalizado para Streamlit para una aplicación de gestión de inventarios y ventas

[theme]
base="dark"
primaryColor="#63C7B2"  # Verde menta para interactividad
backgroundColor="#512DA8"  # Azul oscuro para el fondo principal
secondaryBackgroundColor="#7C4DFF"  # Azul pizarra más oscuro para fondos secundarios
textColor="#FFFFFF"  # Blanco para el texto, asegurando legibilidad
font="sans serif"

[theme.fonts]
heading = "Arial, sans-serif"
base = "Arial, sans-serif"
code = "Monospace"
