# Tema personalizado para Streamlit para una aplicación de gestión de inventarios y ventas

[theme]
base="dark"
primaryColor="#63C7B2"  # Verde menta para interactividad
backgroundColor="#23395D"  # Azul oscuro para el fondo principal
secondaryBackgroundColor="#E8E9EB"  # Gris claro para fondos secundarios
textColor="#FFFFFF"  # Blanco para el texto, asegurando legibilidad
font="sans serif"

[theme.fonts]
heading = "Arial, sans-serif"
base = "Arial, sans-serif"
code = "Monospace"
