# Tema personalizado para Streamlit basado en la paleta proporcionada

[theme]
base="light"
primaryColor="#ee6c4d"  # Coral para elementos activos y destacados
backgroundColor="#e0fbfc"  # Azul muy claro para el fondo principal
secondaryBackgroundColor="#98c1d9"  # Azul cielo para fondos de elementos secundarios
textColor="#293241"  # Azul oscuro profundo para texto, asegurando excelente legibilidad
font="sans serif"

[theme.fonts]
heading = "Helvetica, Arial, sans-serif"
base = "Helvetica, Arial, sans-serif"
code = "Monospace"
